server:
  port: 8080

jwt:
  secret: supersecretpassword45741
  refreshSecret: opicak5444

spring:
  datasource:
    url: postgres://iaofrlqtcaibxj:2803be4c01ec1ce1f96fb9520e6a6238cf4a026faddc5dd323a26962ffd16d12@ec2-34-247-72-29.eu-west-1.compute.amazonaws.com:5432/d6cbi22okrl152
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
