server:
  port: 8080

jwt:
  secret: supersecretpassword45741
  refreshSecret: opicak5444

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /api-docs-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  devtools:
    livereload:
      enabled: true
